---
version: 2
models:
- name: "pipeline_with_models__basketball_player_performance"
  tags:
  - "prophecy_temp"
- name: "pipeline_with_models__player_financials_and_compensation"
  tags:
  - "prophecy_temp"
- name: "pipeline_with_models__player_profiles"
  tags:
  - "prophecy_temp"
